// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpConnStats struct {
	_               structs.HostLayout
	BytesSent       uint64
	BytesReceived   uint64
	PacketsSent     uint64
	PacketsReceived uint64
	StartTs         uint64
	LastTs          uint64
}

type tcpConnTuple struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Netns uint32
}

// loadTcp returns the embedded CollectionSpec for tcp.
func loadTcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp: %w", err)
	}

	return spec, err
}

// loadTcpObjects loads tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpObjects
//	*tcpPrograms
//	*tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpSpecs struct {
	tcpProgramSpecs
	tcpMapSpecs
	tcpVariableSpecs
}

// tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpProgramSpecs struct {
	HandleInetSockSetState *ebpf.ProgramSpec `ebpf:"handle_inet_sock_set_state"`
}

// tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpMapSpecs struct {
	TcpConnStats *ebpf.MapSpec `ebpf:"tcp_conn_stats"`
	TcpEvents    *ebpf.MapSpec `ebpf:"tcp_events"`
}

// tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpVariableSpecs struct {
}

// tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpObjects struct {
	tcpPrograms
	tcpMaps
	tcpVariables
}

func (o *tcpObjects) Close() error {
	return _TcpClose(
		&o.tcpPrograms,
		&o.tcpMaps,
	)
}

// tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpMaps struct {
	TcpConnStats *ebpf.Map `ebpf:"tcp_conn_stats"`
	TcpEvents    *ebpf.Map `ebpf:"tcp_events"`
}

func (m *tcpMaps) Close() error {
	return _TcpClose(
		m.TcpConnStats,
		m.TcpEvents,
	)
}

// tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpVariables struct {
}

// tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpPrograms struct {
	HandleInetSockSetState *ebpf.Program `ebpf:"handle_inet_sock_set_state"`
}

func (p *tcpPrograms) Close() error {
	return _TcpClose(
		p.HandleInetSockSetState,
	)
}

func _TcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_x86_bpfel.o
var _TcpBytes []byte
