// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type udpConnStats struct {
	_               structs.HostLayout
	BytesSent       uint64
	BytesReceived   uint64
	PacketsSent     uint64
	PacketsReceived uint64
	StartTs         uint64
	LastTs          uint64
}

type udpConnTuple struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Netns uint32
}

// loadUdp returns the embedded CollectionSpec for udp.
func loadUdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load udp: %w", err)
	}

	return spec, err
}

// loadUdpObjects loads udp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*udpObjects
//	*udpPrograms
//	*udpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// udpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpSpecs struct {
	udpProgramSpecs
	udpMapSpecs
	udpVariableSpecs
}

// udpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpProgramSpecs struct {
	HandleRecvfromEnter *ebpf.ProgramSpec `ebpf:"handle_recvfrom_enter"`
	HandleSendtoEnter   *ebpf.ProgramSpec `ebpf:"handle_sendto_enter"`
}

// udpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpMapSpecs struct {
	UdpEvents    *ebpf.MapSpec `ebpf:"udp_events"`
	UdpFlowStats *ebpf.MapSpec `ebpf:"udp_flow_stats"`
}

// udpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpVariableSpecs struct {
}

// udpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpObjects struct {
	udpPrograms
	udpMaps
	udpVariables
}

func (o *udpObjects) Close() error {
	return _UdpClose(
		&o.udpPrograms,
		&o.udpMaps,
	)
}

// udpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpMaps struct {
	UdpEvents    *ebpf.Map `ebpf:"udp_events"`
	UdpFlowStats *ebpf.Map `ebpf:"udp_flow_stats"`
}

func (m *udpMaps) Close() error {
	return _UdpClose(
		m.UdpEvents,
		m.UdpFlowStats,
	)
}

// udpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpVariables struct {
}

// udpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpPrograms struct {
	HandleRecvfromEnter *ebpf.Program `ebpf:"handle_recvfrom_enter"`
	HandleSendtoEnter   *ebpf.Program `ebpf:"handle_sendto_enter"`
}

func (p *udpPrograms) Close() error {
	return _UdpClose(
		p.HandleRecvfromEnter,
		p.HandleSendtoEnter,
	)
}

func _UdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed udp_x86_bpfel.o
var _UdpBytes []byte
